<?php

declare(strict_types=1);

/**
 * Bootstrap for the Buzz API sample.
 *
 * Registers class autoloading (Composer's autoloader if `composer install` has
 * been run, otherwise a minimal built-in PSR-4 autoloader — the sample has no
 * runtime dependencies, so it works either way) and provides helpers for
 * reading and writing the platform-standard PHP configuration file.
 */

// ── Autoloading ────────────────────────────────────────────────────────────────
$composerAutoload = __DIR__ . '/vendor/autoload.php';
if (is_file($composerAutoload)) {
    require $composerAutoload;
} else {
    spl_autoload_register(static function (string $class): void {
        $prefix = 'Agilix\\BuzzApi\\';
        if (strncmp($class, $prefix, strlen($prefix)) !== 0) {
            return;
        }
        $relative = substr($class, strlen($prefix));
        $file = __DIR__ . '/src/' . str_replace('\\', '/', $relative) . '.php';
        if (is_file($file)) {
            require $file;
        }
    });
}

// ── Configuration ───────────────────────────────────────────────────────────────
const BUZZ_CONFIG_FILE = __DIR__ . '/buzz-config.php';

const BUZZ_CONFIG_KEYS = [
    'serverUrl', 'contactInformation', 'applicationInformation',
    'oauthUserId', 'oauthKid', 'privateKeyPath',
];

const BUZZ_CONFIG_REQUIRED = ['serverUrl', 'oauthUserId', 'oauthKid', 'privateKeyPath'];

/**
 * Load and validate the configuration array from buzz-config.php.
 *
 * @return array<string,string>
 */
function buzz_load_config(): array
{
    if (!is_file(BUZZ_CONFIG_FILE)) {
        fwrite(STDERR,
            "Configuration not found (buzz-config.php).\n"
            . "  Run setup:  php scripts/run-buzz-sample.php\n"
            . "  or copy buzz-config.example.php to buzz-config.php and fill it in (see README.md).\n");
        exit(1);
    }

    /** @var mixed $config */
    $config = require BUZZ_CONFIG_FILE;
    if (!is_array($config)) {
        fwrite(STDERR, "buzz-config.php must return an array.\n");
        exit(1);
    }

    $missing = [];
    foreach (BUZZ_CONFIG_REQUIRED as $key) {
        if (empty($config[$key])) {
            $missing[] = $key;
        }
    }
    if ($missing) {
        fwrite(STDERR, 'Missing required configuration: ' . implode(', ', $missing) . "\n");
        exit(1);
    }

    // Normalise: ensure all known keys exist.
    $result = [];
    foreach (BUZZ_CONFIG_KEYS as $key) {
        $result[$key] = (string) ($config[$key] ?? '');
    }
    return $result;
}

/**
 * Write the configuration array to buzz-config.php.  Returns the path written.
 *
 * @param array<string,string> $config
 */
function buzz_write_config(array $config): string
{
    $lines = ["<?php", "", "// Buzz API sample configuration — generated by setup.  Do not commit this file.", "return ["];
    foreach (BUZZ_CONFIG_KEYS as $key) {
        $lines[] = sprintf("    %s => %s,", var_export($key, true), var_export((string) ($config[$key] ?? ''), true));
    }
    $lines[] = "];";
    file_put_contents(BUZZ_CONFIG_FILE, implode("\n", $lines) . "\n");
    return BUZZ_CONFIG_FILE;
}
